Document lint warning in osd_mam.sv
VCS has noted the following lint warning:

Lint-[MSIVD] Missing static keyword
xxx/osd-hw/modules/mam/common/osd_mam.sv, 77
  An explicit static keyword shall be required when an initialization value is
  specified as part of a static variable's declaration.
  Please refer to LRM 1800-2009, section 6.21.

However, Verilator 3.902 says:
ERROR: %Error: ../src/opensocdebug_modules_mam_0/common/osd_mam.sv:77:
Unsupported: Static in this context